const drinks = [
    {
    _id: '1',
    name: 'Grey Goose Vodka',
    description: 'A vodka from Russia? Enjoy.',
    brand: 'Grey Goose',
    category: 'Liquor',
    price: 79.99,
    countInStock: 0,
    rating: 5,
    numReviews: 3,
    image: '/images/greygoose.jpg',
},
{
    _id: '2',
    name: 'Black Label',
    description: 'The expensive stuff. Time to get lit',
    brand: 'Johnnie Walker',
    category: 'Liquor',
    price: 149.99,
    countInStock: 15,
    rating: 5,
    numReviews: 2,
    image: '/images/blacklabel.jpg',
},
{
    _id: '3',
    name: 'Fireball',
    description: 'For the hipsters out of Brooklyn. Enjoy.',
    brand: 'Fireball',
    category: 'Liquor',
    price: 19.99,
    countInStock: 17,
    rating: 4,
    numReviews: 7,
    image: '/images/fireball.jpg',
},
{
    _id: '4',
    name: 'Canned Bread',
    description: 'Squidward loves this stuff.',
    brand: 'Tentacle Acres',
    category: 'Beer',
    price: 9.99,
    countInStock: 11,
    rating: 3,
    numReviews: 1,
    image: '/images/cannedbread.jpg',
},
{
    _id: '5',
    name: 'Bloxy Cola',
    description: 'Quench your thirst. Roblox players only.',
    brand: 'Roblox',
    category: 'Beer',
    price: 4.99,
    countInStock: 9,
    rating: 5,
    numReviews: 3,
    image: '/images/bloxycola.jpg',
},
{
    _id: '6',
    name: 'Chilean Cabernet',
    description: 'Cabernet wine from Chile.',
    brand: 'Gato Negro',
    category: 'Wine',
    price: 12.99,
    countInStock: 17,
    rating: 5,
    numReviews: 7,
    image: '/images/gatonegro.jpg',
},
]

module.exports = drinks;